import pandas as pd
import sqlalchemy
from sqlalchemy.exc import SQLAlchemyError
import psycopg2
from psycopg2 import Error

try:
    df = pd.read_csv("full.csv", sep=";",error_bad_lines=False)
    engine = sqlalchemy.create_engine('postgresql://postgres:wD5pem$n@localhost:5432')
    df.to_sql('malwaredatas',engine, if_exists='append')
    

except SQLAlchemyError as e:
    print(e)

try:
    
    connection = psycopg2.connect(user="postgres",
                        password = "wD5pem$n",
                        host= "localhost",
                        port = "5432",
                        database="postgres")
    

    print("Database'e Bağlandı")
    print("******************************")
    cursor = connection.cursor()   

    
    
    print("********* malwaredatas table *********")
    cursor.execute("SELECT COUNT(*) FROM malwaredatas")
    number_of_rows_for_malwaredatas= cursor.fetchone()
    print("Toplam Veri Sayısı: "+str(number_of_rows_for_malwaredatas[0]))
    print("******************************")    
    cursor.execute("SELECT COUNT(DISTINCT sha256_hash) FROM malwaredatas")
    number_of_uniq_rows_for_malwaredatas = cursor.fetchone()
    print("Unique Veri Sayısı: "+str(number_of_uniq_rows_for_malwaredatas[0]))
    print("******************************")
    
    
   
    
    
except (Exception, Error) as error:
    print("Error while connecting to PostgreSQL", error)
finally:
    if (connection):
        cursor.close()
        connection.close()
        print("Database Kapandı")